name:                todoapp-servant
version:             0.1.0.0
github:              "githubuser/todoapp-servant"
license:             BSD-3-Clause
author:              "truthixify"
maintainer:          "truthixify@gmail.com"
copyright:           "2025 truthixify"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/todoapp-servant#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- text
- time
- servant-blaze
- blaze-html  
- http-media     
- wai-cors     
- wai-extra 
- http-api-data
- hspec-wai

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  todoapp-servant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - todoapp-servant

tests:
  todoapp-servant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - todoapp-servant
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
